- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add current user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Configure Docker security settings
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "userns-remap": "default"
      }