name: CI Workflow Java Mgn Time

on:
  push:
    branches:
      - main
      - Lab3
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Wrap gradle
        run: cd app_java |
             gradle wrapper

      - name: Build with Gradle
        run: .app_java/gradlew build --no-daemon

      - name: Run tests
        run: .app_java/gradlew test --no-daemon

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          docker build -t java-spring-app:latest .
